# https://taskfile.dev

version: '3'

tasks:
  deploy:
    cmds:
      - azd auth login
      - azd up
  load-azd-env:
    cmds:
      - |
        echo "Loading azd .env file from current environment..."
        while IFS='=' read -r key value; do
            value=$(echo "$value" | sed 's/^"//' | sed 's/"$//')
            export "$key=$value"
        done <<EOF
        $(azd env get-values)
        EOF
  devtunnel:create:
    cmds:
      - |
        devtunnel login
        devtunnel create aicontactcentre --allow-anonymous
        devtunnel port create -p 8000
  devtunnel:host:
    cmds:
      - devtunnel host aicontactcentre
  api:run:
    deps:
      - load-azd-env
    dir: api
    cmds:
      - uv run fastapi dev