# https://taskfile.dev

version: '3'

tasks:
  setup:infra:
    cmds:
      - azd auth login
      - azd up
  setup:devtunnel:
    cmds:
      - |
        devtunnel login
        devtunnel create aicontactcentre234 --allow-anonymous
        devtunnel port create -p 8000
  run:devtunnel:
    cmds:
      - devtunnel host aicontactcentre234
  run:api:
    dir: api
    cmds:
      - uv run fastapi dev
  run:
    deps: [run:devtunnel, run:api]
  eval:
    dir: eval
    cmds:
      - uv run main.py
