# https://taskfile.dev

version: '3'

tasks:
  devtunnel:create:
    cmds:
      - |
        devtunnel login
        devtunnel create aicontactcentre --allow-anonymous
        devtunnel port create -p 8000
  devtunnel:host:
    cmds:
      - devtunnel host aicontactcentre
  api:
    dir: api
    cmds:
      - uv run fastapi dev
